import {defineField, defineType, defineArrayMember} from 'sanity'

export const service = defineType({
  name: 'service',
  title: 'Offer',
  type: 'document',
  description: 'The things people can book: a single session, the three-month programme, Moonlight Meditation, retreats.',
  groups: [
    {name: 'main', title: 'Main', default: true},
    {name: 'details', title: 'Details and booking'},
    {name: 'seo', title: 'Search and sharing'},
  ],
  fields: [
    defineField({name: 'title', title: 'Name', type: 'localeString', group: 'main', validation: (rule) => rule.required()}),
    defineField({
      name: 'slug',
      title: 'Web address ending',
      type: 'slug',
      group: 'main',
      description: 'Made from the name. Only change it if you must; old links will stop working.',
      options: {source: 'title.en', maxLength: 60},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'kind',
      title: 'What kind of offer is this?',
      type: 'string',
      group: 'main',
      options: {
        layout: 'radio',
        list: [
          {title: 'One-to-one session', value: 'session'},
          {title: 'Longer programme', value: 'programme'},
          {title: 'Group event (in person)', value: 'group'},
          {title: 'Online and free', value: 'free'},
          {title: 'Retreat', value: 'retreat'},
          {title: 'Workshop or circle', value: 'workshop'},
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'summary',
      title: 'Short description',
      type: 'localeText',
      group: 'main',
      description: 'Two or three sentences. This is what appears on the home page and at the top of the offer.',
      validation: (rule) => rule.required(),
    }),
    defineField({name: 'body', title: 'Full description', type: 'localeBlock', group: 'main', description: 'Optional. Shown on the Work with me page under the short description.'}),
    defineField({
      name: 'includes',
      title: 'What is included',
      type: 'array',
      group: 'main',
      description: 'One item per line. For the programme: "Weekly sessions", "Text and email support between sessions", and so on.',
      of: [defineArrayMember({type: 'localeString'})],
    }),
    defineField({name: 'image', title: 'Photo', type: 'photo', group: 'main'}),
    defineField({name: 'price', title: 'Price', type: 'price', group: 'details'}),
    defineField({
      name: 'durationMinutes',
      title: 'How long it lasts, in minutes',
      type: 'object',
      group: 'details',
      description: 'Enter the shortest and longest, for example 60 and 75. For a 2 to 3 hour event enter 120 and 180.',
      fields: [
        defineField({name: 'min', title: 'From', type: 'number', validation: (rule) => rule.min(0)}),
        defineField({name: 'max', title: 'To', type: 'number', validation: (rule) => rule.min(0)}),
      ],
    }),
    defineField({
      name: 'frequency',
      title: 'How often',
      type: 'localeString',
      group: 'details',
      description: 'Optional. For example "Weekly for three months" or "Once a month".',
    }),
    defineField({
      name: 'where',
      title: 'Where',
      type: 'array',
      group: 'details',
      of: [defineArrayMember({type: 'string'})],
      options: {list: [{title: 'In person', value: 'inPerson'}, {title: 'Online', value: 'online'}]},
      initialValue: ['inPerson', 'online'],
    }),
    defineField({
      name: 'modalities',
      title: 'Modalities this can include',
      type: 'array',
      group: 'details',
      description: 'The ingredients. Pick from the modalities list.',
      of: [defineArrayMember({type: 'reference', to: [{type: 'modality'}]})],
    }),
    defineField({name: 'booking', title: 'How people book', type: 'booking', group: 'details'}),
    defineField({
      name: 'showOnHome',
      title: 'Show on the home page',
      type: 'boolean',
      group: 'details',
      initialValue: false,
      description: 'Only the two main offers should be on. Others still appear on Work with me or Groups and retreats.',
    }),
    defineField({name: 'order', title: 'Position in lists', type: 'number', group: 'details', description: 'Lower numbers come first.', initialValue: 10}),
    defineField({name: 'seo', title: 'Search and sharing', type: 'seo', group: 'seo'}),
  ],
  orderings: [{title: 'Position', name: 'order', by: [{field: 'order', direction: 'asc'}]}],
  preview: {
    select: {title: 'title.en', amount: 'price.amount', currency: 'price.currency', kind: 'kind', media: 'image'},
    prepare: ({title, amount, currency, kind, media}) => ({
      title,
      subtitle: [kind, amount ? `${currency === 'MUR' ? 'Rs' : currency} ${amount.toLocaleString('en-GB')}` : 'no published price'].filter(Boolean).join(' · '),
      media,
    }),
  },
})
