import {defineField, defineType} from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Contact details and links',
  type: 'document',
  groups: [
    {name: 'contact', title: 'Contact', default: true},
    {name: 'links', title: 'Booking and social links'},
    {name: 'policies', title: 'Policies and small print'},
    {name: 'seo', title: 'Search and sharing'},
  ],
  fields: [
    defineField({name: 'siteName', title: 'Practice name', type: 'string', initialValue: 'Origine Healing', group: 'contact'}),
    defineField({name: 'practitionerName', title: 'Your name', type: 'string', initialValue: 'Stephanie Maurel', group: 'contact'}),
    defineField({
      name: 'tagline',
      title: 'One-line description of the practice',
      type: 'localeString',
      description: 'Used in the browser tab and in Google results. Example: "Embodied healing in the north of Mauritius and online."',
      group: 'contact',
    }),
    defineField({name: 'email', title: 'Email address', type: 'string', description: 'Where enquiry-form messages are sent and what is shown on the Contact page.', group: 'contact', validation: (rule) => rule.email()}),
    defineField({name: 'whatsapp', title: 'WhatsApp number', type: 'string', description: 'With country code, no spaces. Example: +23052520605', group: 'contact'}),
    defineField({name: 'phone', title: 'Phone number to display (optional)', type: 'string', group: 'contact'}),
    defineField({
      name: 'address',
      title: 'Where you practise',
      type: 'object',
      group: 'contact',
      fields: [
        defineField({name: 'venue', title: 'Venue', type: 'string', initialValue: 'Domaine de Labourdonnais'}),
        defineField({name: 'street', title: 'Street or building (optional)', type: 'string'}),
        defineField({name: 'town', title: 'Town', type: 'string', initialValue: 'Mapou'}),
        defineField({name: 'region', title: 'Region', type: 'string', initialValue: 'Rivière du Rempart'}),
        defineField({name: 'country', title: 'Country', type: 'string', initialValue: 'Mauritius'}),
        defineField({name: 'mapUrl', title: 'Google Maps link (optional)', type: 'url'}),
        defineField({name: 'directions', title: 'Directions or arrival note (optional)', type: 'localeText'}),
      ],
    }),
    defineField({name: 'calendlyUrl', title: 'Calendly booking link', type: 'url', initialValue: 'https://calendly.com/stephanie-origine/60mins', group: 'links'}),
    defineField({name: 'youtubeUrl', title: 'YouTube channel', type: 'url', initialValue: 'https://www.youtube.com/@OrigineMeditations', group: 'links'}),
    defineField({name: 'instagramUrl', title: 'Instagram', type: 'url', initialValue: 'https://instagram.com/stephaniemaurel', group: 'links'}),
    defineField({name: 'facebookUrl', title: 'Facebook', type: 'url', initialValue: 'https://facebook.com/stephmaurel', group: 'links'}),
    defineField({
      name: 'newsletterFormUrl',
      title: 'Newsletter sign-up form address (Kit)',
      type: 'url',
      description: 'The "action" address of your Kit form. Found in Kit under the form\'s Embed → HTML. The site posts email addresses there.',
      group: 'links',
    }),
    defineField({
      name: 'newsletterFormUid',
      title: 'Newsletter form ID (Kit)',
      type: 'string',
      description: 'The short code in the Kit form address, for example "a1b2c3d4e5". Optional but helps Kit record where sign-ups came from.',
      group: 'links',
    }),
    defineField({
      name: 'replyPromise',
      title: 'Reply promise',
      type: 'localeString',
      description: 'Shown next to the contact form. Example: "I reply within one business day."',
      group: 'policies',
    }),
    defineField({
      name: 'cancellationPolicy',
      title: 'Cancellation policy',
      type: 'localeText',
      description: 'Shown on Work with me and in the FAQ.',
      group: 'policies',
    }),
    defineField({name: 'photoCredit', title: 'Photography credit', type: 'string', initialValue: 'Photography by Sita Kelly Photography', group: 'policies'}),
    defineField({name: 'photoCreditUrl', title: 'Photographer link (optional)', type: 'url', group: 'policies'}),
    defineField({
      name: 'defaultSeo',
      title: 'Default search and sharing settings',
      type: 'seo',
      description: 'Used by any page that does not set its own.',
      group: 'seo',
    }),
  ],
  preview: {prepare: () => ({title: 'Contact details and links'})},
})
